export interface MenuItem {
    label: string
    icon: string
    href?: string
    description?: string
    showSidebar: boolean
    disabled: boolean
    items?: MenuItem[]
  }
  
  export const MenuItems: MenuItem[] = [
    {
      label: 'Admin Panel',
      icon: 'solar:home-angle-outline',
      href: '/v1',
      description: 'Dashboard',
      showSidebar: true,
      disabled: false,
    },
    {
      label: 'Cyber Threat Intelligence',
      icon: 'streamline:artificial-intelligence-spark',
      showSidebar: true,
      disabled: true,
      href: '/v1/cti',
      items: [
        {
          label: 'Threat Actor Tracking',
          icon: 'tdesign:user-unknown',
          description: 'ICS Intelligence',
          href: '/v1/ti/threat_actors',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Threat Hunting',
          icon: 'uil:hunting',
          description: 'Threat Hunting',
          href: '/v1/ti/threat_hunting',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Malware Intelligence',
          icon: 'jam:skull',
          description: 'Malware Intelligence',
          href: '/v1/ti/malware_intelligence',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Vulnerability Intelligence',
          description: 'Monitoring Management',
          href: '/v1/vuln/dashboard',
          icon: 'tabler:layout-dashboard',
          showSidebar: true,
          disabled: true,
        },
        {
          label: 'IOC / IOA Management',
          icon: 'uil:hunting',
          description: 'Threat Hunting',
          href: '/v1/ti/threat_hunting',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Breach Datasets',
          icon: 'icon-park-outline:data-lock',
          description: 'Search engine for exposed sensitive data on the dark web',
          href: '/v1/ti/mitre',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Dark Web News',
          icon: 'icon-park-outline:data-lock',
          description: 'Search engine for exposed sensitive data on the dark web',
          href: '/v1/ti/mitre',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Offensive Cyber Operations',
          icon: 'icon-park-outline:data-lock',
          description: 'ICS Intelligence',
          href: '/v1/ti/mitre',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Geopolitical Intelligence',
          icon: 'healthicons:world-care-outline',
          description: 'ICS Intelligence',
          href: '/v1/ics/mitre',
          showSidebar: true,
          disabled: false,
        },
      ],
    },
    {
      label: 'ICS Intelligence',
      icon: 'material-symbols:health-metrics',
      showSidebar: true,
      disabled: true,
      href: '/v1/ics',
      items: [
        {
          label: 'Threat Detection',
          icon: 'material-symbols:detection-and-zone',
          description: 'ICS Intelligence',
          href: '/v1/ics/threat_detection',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Hunter Devices',
          description: 'Hunter Devices',
          href: '/v1/vuln/devices',
          icon: 'carbon:iot-connect',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'OT Cyber Threats',
          icon: 'mdi:office-building-cog-outline',
          description: 'ICS Intelligence',
          href: '/v1/ics/ot_theats',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Mitre Attack',
          icon: 'material-symbols:mitre-outline-rounded',
          description: 'ICS Intelligence',
          href: '/v1/ics/mitre',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Risk Analysis',
          icon: 'grommet-icons:risk',
          description: 'ICS Intelligence',
          href: '/v1/ics/risk_analysis',
          showSidebar: true,
          disabled: false,
        },
      ],
    },
    {
      label: 'Attack Surface Management',
      icon: 'mdi:sword-cross',
      showSidebar: true,
      disabled: true,
      href: '/v1/ics',
      items: [
        {
          label: 'Reconnaissance',
          icon: 'carbon:cloud-monitoring',
          showSidebar: true,
          disabled: false,
          href: '/v1/tracking',
          description: 'Tracking Management',
        },
        {
          label: 'Digital Asset Monitoring',
          description: 'Takedown Management',
          icon: 'mdi:lan-disconnect',
          href: '/v1/takedown',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Vulnerability Detection',
          description: 'Takedown Management',
          icon: 'mdi:lan-disconnect',
          href: '/v1/takedown',
          showSidebar: true,
          disabled: false,
        },
      ],
    },
  
    {
      label: 'Brand Protection',
      icon: 'material-symbols:shield',
      showSidebar: true,
      disabled: true,
      href: '/v1/ics',
      items: [
        {
          label: 'Fraud Protection',
          description: 'Takedown Management',
          icon: 'mdi:lan-disconnect',
          href: '/v1/takedown',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'VIP Protection',
          icon: 'carbon:cloud-monitoring',
          showSidebar: true,
          disabled: false,
          href: '/v1/tracking',
          description: 'Tracking Management',
        },
        {
          label: 'Takedown',
          description: 'Takedown Management',
          icon: 'mdi:lan-disconnect',
          href: '/v1/takedown',
          showSidebar: true,
          disabled: false,
        },
      ],
    },
    {
      label: 'Supply Chain',
      icon: 'hugeicons:shield-blockchain',
      showSidebar: true,
      disabled: true,
      description: 'Tracking Management',
      items: [
        {
          label: 'Analytics Board',
          icon: 'healthicons:world-care-outline',
          description: 'ICS Intelligence',
          href: '/v1/ics/mitre',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Third Party Companies',
          icon: 'healthicons:world-care-outline',
          description: 'ICS Intelligence',
          href: '/v1/ics/mitre',
          showSidebar: true,
          disabled: false,
        },
      ],
    },
    {
      label: 'Alerts',
      icon: 'ant-design:alert-outlined',
      showSidebar: true,
      disabled: false,
      href: '/v1/alerts',
    },
  ]
  
  export const MenuItemsBottom: MenuItem[] = [
    {
      label: 'On-Demand Services',
      icon: 'icon-park-outline:sales-report',
      showSidebar: true,
      disabled: false,
      items: [
        {
          label: 'Forensic Analysis',
          description: 'Analytics Management',
          href: '/v1/analytics/cti',
          icon: 'fluent:microscope-24-filled',
          showSidebar: true,
          disabled: true,
        },
        {
          label: 'SOC Intelligence',
          icon: 'line-md:monitor-mutlple',
          description: 'ICS Intelligence',
          href: '/v1/soc',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Pentest',
          description: 'Analytics Management',
          href: '/v1/analytics/cti',
          icon: 'carbon:transform-instructions',
          showSidebar: true,
          disabled: true,
        },
      ],
    },
    {
      label: 'Reports',
      icon: 'icon-park-outline:sales-report',
      showSidebar: true,
      disabled: false,
      items: [
        {
          label: 'Bulletins',
          description: 'Analytics Management',
          href: '/v1/analytics/cti',
          icon: 'fluent:text-bullet-list-square-sparkle-16-filled',
          showSidebar: true,
          disabled: true,
        },
        {
          label: 'My Reports',
          description: 'Reports Management',
          href: '/v1/analytics/reports',
          icon: 'bxs:report',
          showSidebar: true,
          disabled: true,
        },
      ],
    },
  
    {
      label: 'Support',
      icon: 'fluent:person-support-32-filled',
      showSidebar: true,
      disabled: false,
      items: [
        {
          label: 'My Tickets',
          description: 'Service Desk',
          href: '/v1/servicedesk',
          icon: 'fluent-mdl2:all-apps',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'Open Ticket',
          description: 'Service Desk',
          href: '/v1/servicedesk/open',
          icon: 'akar-icons:chat-add',
          showSidebar: true,
          disabled: false,
        },
      ],
    },
    {
      label: 'Threat Intelligence Analyst',
      icon: 'fluent:person-support-32-filled',
      showSidebar: true,
      disabled: false,
      items: [
        {
          label: 'User Management',
          icon: 'carbon:group-security',
          showSidebar: true,
          disabled: true,
          items: [
            {
              label: 'Users',
              description: '',
              href: '/admin/acl/users',
              icon: 'clarity:users-solid',
              showSidebar: true,
              disabled: false,
            },
            {
              label: 'Roles',
              description: '',
              href: '/admin/acl/roles',
              icon: 'oui:app-users-roles',
              showSidebar: true,
              disabled: false,
            },
          ],
        },
        {
          label: 'Management',
          description: 'Service Desk',
          href: '/v1/servicedesk',
          icon: 'fluent-mdl2:all-apps',
          showSidebar: true,
          disabled: false,
        },
        {
          label: 'My Tasks',
          description: 'Service Desk',
          href: '/v1/servicedesk/open',
          icon: 'akar-icons:chat-add',
          showSidebar: true,
          disabled: false,
        },
      ],
    },
  ]
  
  export const mergedMenu: MenuItem[] = [...MenuItems, ...MenuItemsBottom]